const data = {
    'AGPL-1.0': 'High',
    'AGPL-3.0': 'High',
    'CC-BY-NC-1.0': 'High',
    'CC-BY-NC-2.0': 'High',
    'CC-BY-NC-2.5': 'High',
    'CC-BY-NC-3.0': 'High',
    'CC-BY-NC-4.0': 'High',
    'CC-BY-NC-ND-1.0': 'High',
    'CC-BY-NC-ND-2.0': 'High',
    'CC-BY-NC-ND-2.5': 'High',
    'CC-BY-NC-ND-3.0': 'High',
    'CC-BY-NC-ND-4.0': 'High',
    'CC-BY-NC-SA-1.0': 'High',
    'CC-BY-NC-SA-2.0': 'High',
    'CC-BY-NC-SA-2.5': 'High',
    'CC-BY-NC-SA-3.0': 'High',
    'CC-BY-NC-SA-4.0': 'High',
    'Commons-Clause': 'High',
    'Facebook-2-Clause': 'High',
    'Facebook-3-Clause': 'High',
    'Facebook-Examples': 'High',
    BCL: 'Medium',
    'CC-BY-ND-1.0': 'Medium',
    'CC-BY-ND-2.0': 'Medium',
    'CC-BY-ND-2.5': 'Medium',
    'CC-BY-ND-3.0': 'Medium',
    'CC-BY-ND-4.0': 'Medium',
    'CC-BY-SA-1.0': 'Medium',
    'CC-BY-SA-2.0': 'Medium',
    'CC-BY-SA-2.5': 'Medium',
    'CC-BY-SA-3.0': 'Medium',
    'CC-BY-SA-4.0': 'Medium',
    'GPL-1.0': 'Medium',
    'GPL-2.0': 'Medium',
    'GPL-2.0-with-autoconf-exception': 'Medium',
    'GPL-2.0-with-bison-exception': 'Medium',
    'GPL-2.0-with-classpath-exception': 'Medium',
    'GPL-2.0-with-font-exception': 'Medium',
    'GPL-2.0-with-GCC-exception': 'Medium',
    GPLv2: 'Medium',
    'GPLv2+': 'Medium',
    GPLv3: 'Medium',
    'GPLv3+': 'Medium',
    'GPL-3.0': 'Medium',
    'GPL-3.0-with-autoconf-exception': 'Medium',
    'GPL-3.0-with-GCC-exception': 'Medium',
    'LGPL-2.0': 'Medium',
    'LGPL-2.1': 'Medium',
    'LGPL-3.0': 'Medium',
    'LGPLv2+': 'Medium',
    'NPL-1.0': 'Medium',
    'NPL-1.1': 'Medium',
    'OSL-1.0': 'Medium',
    'OSL-1.1': 'Medium',
    'OSL-2.0': 'Medium',
    'OSL-2.1': 'Medium',
    'OSL-3.0': 'Medium',
    'QPL-1.0': 'Medium',
    Sleepycat: 'Medium',

    'APSL-1.0': 'Low',
    'APSL-1.1': 'Low',
    'APSL-1.2': 'Low',
    'APSL-2.0': 'Low',
    'CDDL-1.0': 'Low',
    'CDDL-1.1': 'Low',
    'CPL-1.0': 'Low',
    'EPL-1.0': 'Low',
    'EPL-2.0': 'Low',
    FreeImage: 'Low',
    'IPL-1.0': 'Low',
    'MPL-1.0': 'Low',
    'MPL-1.1': 'Low',
    'MPL-2.0': 'Low',
    Ruby: 'Low',

    'AFL-1.1': 'Low',
    'AFL-1.2': 'Low',
    'AFL-2.0': 'Low',
    'AFL-2.1': 'Low',
    'AFL-3.0': 'Low',
    'Apache-1.0': 'Low',
    'Apache-1.1': 'Low',
    'Apache-2.0': 'Low',
    'Artistic-1.0-cl8': 'Low',
    'Artistic-1.0-Perl': 'Low',
    'Artistic-1.0': 'Low',
    'Artistic-2.0': 'Low',
    'BSD-2-Clause-FreeBSD': 'Low',
    'BSD-2-Clause-NetBSD': 'Low',
    'BSD-2-Clause': 'Low',
    'BSD-3-Clause-Attribution': 'Low',
    'BSD-3-Clause-Clear': 'Low',
    'BSD-3-Clause-LBNL': 'Low',
    'BSD-3-Clause': 'Low',
    'BSD-4-Clause': 'Low',
    'BSD-4-Clause-UC': 'Low',
    'BSD-Protection': 'Low',
    'BSL-1.0': 'Low',
    'CC-BY-1.0': 'Low',
    'CC-BY-2.0': 'Low',
    'CC-BY-2.5': 'Low',
    'CC-BY-3.0': 'Low',
    'CC-BY-4.0': 'Low',
    FTL: 'Low',
    ImageMagick: 'Low',
    ISC: 'Low',
    Libpng: 'Low',
    'Lil-1.0': 'Low',
    'Linux-OpenIB': 'Low',
    'LPL-1.02': 'Low',
    'LPL-1.0': 'Low',
    MIT: 'Low',
    'MS-PL': 'Low',
    NCSA: 'Low',
    OpenSSL: 'Low',
    'PHP-3.01': 'Low',
    'PHP-3.0': 'Low',
    PIL: 'Low',
    PostgreSQL: 'Low',
    'Python-2.0-complete': 'Low',
    'Python-2.0': 'Low',
    'SGI-B-1.0': 'Low',
    'SGI-B-1.1': 'Low',
    'SGI-B-2.0': 'Low',
    'Unicode-TOU': 'Low',
    'Unicode-DFS-2015': 'Low',
    'Unicode-DFS-2016': 'Low',
    'UPL-1.0': 'Low',
    'W3C-19980720': 'Low',
    'W3C-20150513': 'Low',
    W3C: 'Low',
    X11: 'Low',
    Xnet: 'Low',
    'Zend-2.0': 'Low',
    'zlib-acknowledgement': 'Low',
    Zlib: 'Low',
    'ZPL-1.1': 'Low',
    'ZPL-2.0': 'Low',
    'ZPL-2.1': 'Low',

    Beerware: 'Low',
    'OFL-1.1': 'Low',
    OpenVision: 'Low',
};

const keys = Object.keys(data);
const result:any = [];

for (let i = 0; i < keys.length; i++) {
    result.push({
        label: keys[i],
        value: keys[i],
    });
}

export default result;
